export const GET_USER_BY_ID_INIT = 'GET_USER_BY_ID_INIT';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL';

export const GET_USER_BY_USER_NAME_INIT = 'GET_USER_BY_USER_NAME_INIT';
export const GET_USER_BY_USER_NAME_SUCCESS = 'GET_USER_BY_USER_NAME_SUCCESS';
export const GET_USER_BY_USER_NAME_FAIL = 'GET_USER_BY_USER_NAME_FAIL';
