export const LIKE_ON_A_POST_INIT = 'LIKE_ON_A_POST_INIT';
export const LIKE_ON_A_POST_SUCCESS = 'LIKE_ON_A_POST_SUCCESS';
export const LIKE_ON_A_POST_FAIL = 'LIKE_ON_A_POST_FAIL';

export const LIKE_ON_A_COMMENT_INIT = 'LIKE_ON_A_COMMENT_INIT';
export const LIKE_ON_A_COMMENT_SUCCESS = 'LIKE_ON_A_COMMENT_SUCCESS';
export const LIKE_ON_A_COMMENT_FAIL = 'LIKE_ON_A_COMMENT_FAIL';

export const UNLIKE_ON_A_POST_INIT = 'UNLIKE_ON_A_POST_INIT';
export const UNLIKE_ON_A_POST_SUCCESS = 'UNLIKE_ON_A_POST_SUCCESS';
export const UNLIKE_ON_A_POST_FAIL = 'UNLIKE_ON_A_POST_FAIL';

export const GET_ALL_LIKES_BY_A_USER_INIT = 'GET_ALL_LIKES_BY_A_USER_INIT';
export const GET_ALL_LIKES_BY_A_USER_SUCCESS =
  'GET_ALL_LIKES_BY_A_USER_SUCCESS';
export const GET_ALL_LIKES_BY_A_USER_FAIL = 'GET_ALL_LIKES_BY_A_USER_FAIL';
