export const COMMENT_ON_A_POST_INIT = 'COMMENT_ON_A_POST_INIT';
export const COMMENT_ON_A_POST_SUCCESS = 'COMMENT_ON_A_POST_SUCCESS';
export const COMMENT_ON_A_POST_FAIL = 'COMMENT_ON_A_POST_FAIL';

export const GET_ALL_COMMENTS_ON_A_POST_INIT =
  'GET_ALL_COMMENTS_ON_A_POST_INIT';
export const GET_ALL_COMMENTS_ON_A_POST_SUCCESS =
  'GET_ALL_COMMENTS_ON_A_POST_SUCCESS';
export const GET_ALL_COMMENTS_ON_A_POST_FAIL =
  'GET_ALL_COMMENTS_ON_A_POST_FAIL';
