export const FEED_INIT = 'FEED_INIT';
export const FEED_SUCCESS = 'FEED_SUCCESS';
export const FEED_FAIL = 'FEED_FAIL';

export const FEED_BY_USER_ID_INIT = 'FEED_BY_USER_ID_INIT';
export const FEED_BY_USER_ID_SUCCESS = 'FEED_BY_USER_ID_SUCCESS';
export const FEED_BY_USER_ID_FAIL = 'FEED_BY_USER_ID_FAIL';
